apiVersion: v1
kind: Service
metadata:
  name: ms-ocp-matrix-retrieveproductinstances-graphql
  labels:
    app: ms-ocp-matrix-retrieveproductinstances-graphql
spec:
  selector:
    app: ms-ocp-matrix-retrieveproductinstances-graphql
  ports:
    - name: http
      port: 8080
      targetPort: 8080
